
language: "en"

pipeline:
- name: "nlp_spacy"             
- name: "tokenizer_spacy"       
- name: "ner_crf"               
- name: "intent_featurizer_spacy"   
- name: "intent_classifier_sklearn"   
- name: "ner_synonyms"              
